name: m2-dev-branch-updater

on:
  schedule:
    - cron:  '0 0 * * 5'    # every friday


jobs:
  magento-updater:
    runs-on: ubuntu-latest
    name: 'weekly updater'
    steps:
      - uses: actions/checkout@v2 
        with:
          submodules: recursive
          persist-credentials: false
          token: ${{secrets.PAT}}
      - name: Weekly auto-updater
        run: |
          cd magento
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git config --global pull.rebase true
          git checkout 2.4-develop
          git pull
          cd ..
          git add magento
          git commit -m 'weekly update'
          git push
        
  
